  -- ==================== AUTO-GENERATED IMGUI FUNCTIONS ====================
  -- Generated by imgui_api_generator.py
  -- Date: 2025-05-30 16:46:38

  ImGui_AcceptDragDropPayload = function(ctx, label, value)
    log_api_call("ImGui_AcceptDragDropPayload", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_AcceptDragDropPayloadFiles = function(ctx, label, value)
    log_api_call("ImGui_AcceptDragDropPayloadFiles", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_AcceptDragDropPayloadRGB = function(ctx, label, value)
    log_api_call("ImGui_AcceptDragDropPayloadRGB", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_AcceptDragDropPayloadRGBA = function(ctx, label, value)
    log_api_call("ImGui_AcceptDragDropPayloadRGBA", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_AlignTextToFramePadding = function(ctx, text)
    log_api_call("ImGui_AlignTextToFramePadding", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_BeginChild = function(ctx)
    log_api_call("ImGui_BeginChild", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginDisabled = function(ctx)
    log_api_call("ImGui_BeginDisabled", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginDragDropSource = function(ctx)
    log_api_call("ImGui_BeginDragDropSource", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginDragDropTarget = function(ctx)
    log_api_call("ImGui_BeginDragDropTarget", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginItemTooltip = function(ctx)
    log_api_call("ImGui_BeginItemTooltip", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginMainMenuBar = function(ctx)
    log_api_call("ImGui_BeginMainMenuBar", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginPopup = function(ctx)
    log_api_call("ImGui_BeginPopup", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginPopupContextItem = function(ctx)
    log_api_call("ImGui_BeginPopupContextItem", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginPopupContextWindow = function(ctx)
    log_api_call("ImGui_BeginPopupContextWindow", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginPopupModal = function(ctx)
    log_api_call("ImGui_BeginPopupModal", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_BeginTable = function(ctx)
    log_api_call("ImGui_BeginTable", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_Bullet = function(ctx)
    log_api_call("ImGui_Bullet", ctx)
    -- Default virtual implementation
  end,

  ImGui_CalcItemWidth = function(ctx)
    log_api_call("ImGui_CalcItemWidth", ctx)
    -- Default virtual implementation
  end,

  ImGui_CalcTextSize = function(ctx, text, width, height)
    log_api_call("ImGui_CalcTextSize", ctx, text, width, height)
    -- Default virtual implementation
  end,

  ImGui_CloseCurrentPopup = function(ctx)
    log_api_call("ImGui_CloseCurrentPopup", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_CollapsingHeader = function(ctx)
    log_api_call("ImGui_CollapsingHeader", ctx)
    -- Default virtual implementation
  end,

  ImGui_ColorButton = function(ctx, label, color)
    log_api_call("ImGui_ColorButton", ctx, label, color)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_ColorConvertDouble4ToU32 = function(ctx, color)
    log_api_call("ImGui_ColorConvertDouble4ToU32", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_ColorConvertHSVtoRGB = function(ctx, color)
    log_api_call("ImGui_ColorConvertHSVtoRGB", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_ColorEdit3 = function(ctx, color)
    log_api_call("ImGui_ColorEdit3", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_ColorEdit4 = function(ctx, color)
    log_api_call("ImGui_ColorEdit4", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_ColorPicker3 = function(ctx, color)
    log_api_call("ImGui_ColorPicker3", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_ColorPicker4 = function(ctx, color)
    log_api_call("ImGui_ColorPicker4", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_Columns = function(ctx)
    log_api_call("ImGui_Columns", ctx)
    -- Default virtual implementation
  end,

  ImGui_CreateDrawListSplitter = function(ctx)
    log_api_call("ImGui_CreateDrawListSplitter", ctx)
    -- Default virtual implementation
  end,

  ImGui_CreateFunctionFromEEL = function(ctx)
    log_api_call("ImGui_CreateFunctionFromEEL", ctx)
    -- Default virtual implementation
  end,

  ImGui_CreateImageFromMem = function(ctx, text)
    log_api_call("ImGui_CreateImageFromMem", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_CreateListClipper = function(ctx)
    log_api_call("ImGui_CreateListClipper", ctx)
    -- Default virtual implementation
  end,

  ImGui_CreateTextFilter = function(ctx, text)
    log_api_call("ImGui_CreateTextFilter", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_DebugFlashStyleColor = function(ctx, color)
    log_api_call("ImGui_DebugFlashStyleColor", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_DebugStartItemPicker = function(ctx)
    log_api_call("ImGui_DebugStartItemPicker", ctx)
    -- Default virtual implementation
  end,

  ImGui_DragDouble2 = function(ctx, label, value)
    log_api_call("ImGui_DragDouble2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragDouble3 = function(ctx, label, value)
    log_api_call("ImGui_DragDouble3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragDouble4 = function(ctx, label, value)
    log_api_call("ImGui_DragDouble4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragDoubleN = function(ctx, label, value)
    log_api_call("ImGui_DragDoubleN", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragFloat = function(ctx, label, value)
    log_api_call("ImGui_DragFloat", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragFloatRange2 = function(ctx, label, value)
    log_api_call("ImGui_DragFloatRange2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragInt2 = function(ctx, label, value)
    log_api_call("ImGui_DragInt2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragInt3 = function(ctx, label, value)
    log_api_call("ImGui_DragInt3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragInt4 = function(ctx, label, value)
    log_api_call("ImGui_DragInt4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragIntRange2 = function(ctx, label, value)
    log_api_call("ImGui_DragIntRange2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DragScalar = function(ctx, label, value)
    log_api_call("ImGui_DragScalar", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_DrawListSplitter_Merge = function(ctx)
    log_api_call("ImGui_DrawListSplitter_Merge", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawListSplitter_SetCurrentChannel = function(ctx)
    log_api_call("ImGui_DrawListSplitter_SetCurrentChannel", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawListSplitter_Split = function(ctx)
    log_api_call("ImGui_DrawListSplitter_Split", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddBezierCubic = function(ctx)
    log_api_call("ImGui_DrawList_AddBezierCubic", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddBezierQuadratic = function(ctx)
    log_api_call("ImGui_DrawList_AddBezierQuadratic", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddCircle = function(ctx)
    log_api_call("ImGui_DrawList_AddCircle", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddCircleFilled = function(ctx)
    log_api_call("ImGui_DrawList_AddCircleFilled", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddEllipse = function(ctx)
    log_api_call("ImGui_DrawList_AddEllipse", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddEllipseFilled = function(ctx)
    log_api_call("ImGui_DrawList_AddEllipseFilled", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddImage = function(ctx, text)
    log_api_call("ImGui_DrawList_AddImage", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddLine = function(ctx)
    log_api_call("ImGui_DrawList_AddLine", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddNgon = function(ctx)
    log_api_call("ImGui_DrawList_AddNgon", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddNgonFilled = function(ctx)
    log_api_call("ImGui_DrawList_AddNgonFilled", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddPolyline = function(ctx)
    log_api_call("ImGui_DrawList_AddPolyline", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddRect = function(ctx)
    log_api_call("ImGui_DrawList_AddRect", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddRectFilled = function(ctx)
    log_api_call("ImGui_DrawList_AddRectFilled", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddRectFilledMultiColor = function(ctx, color)
    log_api_call("ImGui_DrawList_AddRectFilledMultiColor", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_DrawList_AddText = function(ctx, text)
    log_api_call("ImGui_DrawList_AddText", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddTextEx = function(ctx, text)
    log_api_call("ImGui_DrawList_AddTextEx", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddTriangle = function(ctx)
    log_api_call("ImGui_DrawList_AddTriangle", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_AddTriangleFilled = function(ctx)
    log_api_call("ImGui_DrawList_AddTriangleFilled", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathArcTo = function(ctx)
    log_api_call("ImGui_DrawList_PathArcTo", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathBezierQuadraticCurveTo = function(ctx)
    log_api_call("ImGui_DrawList_PathBezierQuadraticCurveTo", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathFillConcave = function(ctx)
    log_api_call("ImGui_DrawList_PathFillConcave", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathFillConvex = function(ctx)
    log_api_call("ImGui_DrawList_PathFillConvex", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathLineTo = function(ctx)
    log_api_call("ImGui_DrawList_PathLineTo", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PathStroke = function(ctx)
    log_api_call("ImGui_DrawList_PathStroke", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PopClipRect = function(ctx)
    log_api_call("ImGui_DrawList_PopClipRect", ctx)
    -- Default virtual implementation
  end,

  ImGui_DrawList_PushClipRect = function(ctx)
    log_api_call("ImGui_DrawList_PushClipRect", ctx)
    -- Default virtual implementation
  end,

  ImGui_EndChild = function(ctx)
    log_api_call("ImGui_EndChild", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndDisabled = function(ctx)
    log_api_call("ImGui_EndDisabled", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndDragDropSource = function(ctx)
    log_api_call("ImGui_EndDragDropSource", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndDragDropTarget = function(ctx)
    log_api_call("ImGui_EndDragDropTarget", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndMainMenuBar = function(ctx)
    log_api_call("ImGui_EndMainMenuBar", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndPopup = function(ctx)
    log_api_call("ImGui_EndPopup", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_EndTable = function(ctx)
    log_api_call("ImGui_EndTable", ctx)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_Function_GetValue = function(ctx)
    log_api_call("ImGui_Function_GetValue", ctx)
    -- Default virtual implementation
  end,

  ImGui_Function_GetValue_String = function(ctx)
    log_api_call("ImGui_Function_GetValue_String", ctx)
    -- Default virtual implementation
  end,

  ImGui_Function_SetValue = function(ctx)
    log_api_call("ImGui_Function_SetValue", ctx)
    -- Default virtual implementation
  end,

  ImGui_Function_SetValue_String = function(ctx)
    log_api_call("ImGui_Function_SetValue_String", ctx)
    -- Default virtual implementation
  end,

  ImGui_GetBackgroundDrawList = function(ctx)
    log_api_call("ImGui_GetBackgroundDrawList", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetBuiltinPath = function(ctx)
    log_api_call("ImGui_GetBuiltinPath", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetColor = function(ctx, color)
    log_api_call("ImGui_GetColor", ctx, color)
    -- Return mock values for getter functions
    return 0xFFFFFFFF  -- Mock color
  end,

  ImGui_GetColorEx = function(ctx, color)
    log_api_call("ImGui_GetColorEx", ctx, color)
    -- Return mock values for getter functions
    return 0xFFFFFFFF  -- Mock color
  end,

  ImGui_GetColorU32 = function(ctx, color)
    log_api_call("ImGui_GetColorU32", ctx, color)
    -- Return mock values for getter functions
    return 0xFFFFFFFF  -- Mock color
  end,

  ImGui_GetColumnIndex = function(ctx)
    log_api_call("ImGui_GetColumnIndex", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetColumnOffset = function(ctx)
    log_api_call("ImGui_GetColumnOffset", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetColumnWidth = function(ctx)
    log_api_call("ImGui_GetColumnWidth", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetConfigVar = function(ctx)
    log_api_call("ImGui_GetConfigVar", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetContentRegionAvail = function(ctx)
    log_api_call("ImGui_GetContentRegionAvail", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetCursorPos = function(ctx)
    log_api_call("ImGui_GetCursorPos", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetCursorPosX = function(ctx)
    log_api_call("ImGui_GetCursorPosX", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetCursorScreenPos = function(ctx)
    log_api_call("ImGui_GetCursorScreenPos", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetCursorStartPos = function(ctx)
    log_api_call("ImGui_GetCursorStartPos", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetDeltaTime = function(ctx)
    log_api_call("ImGui_GetDeltaTime", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetDragDropPayloadFile = function(ctx)
    log_api_call("ImGui_GetDragDropPayloadFile", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetFont = function(ctx)
    log_api_call("ImGui_GetFont", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetFontSize = function(ctx)
    log_api_call("ImGui_GetFontSize", ctx)
    -- Return mock values for getter functions
    return 100, 50  -- Mock width, height
  end,

  ImGui_GetForegroundDrawList = function(ctx)
    log_api_call("ImGui_GetForegroundDrawList", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetFrameCount = function(ctx)
    log_api_call("ImGui_GetFrameCount", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetFrameHeight = function(ctx)
    log_api_call("ImGui_GetFrameHeight", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetFrameHeightWithSpacing = function(ctx)
    log_api_call("ImGui_GetFrameHeightWithSpacing", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetIO = function(ctx)
    log_api_call("ImGui_GetIO", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetInputQueueCharacter = function(ctx)
    log_api_call("ImGui_GetInputQueueCharacter", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetItemID = function(ctx)
    log_api_call("ImGui_GetItemID", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetItemRectMax = function(ctx)
    log_api_call("ImGui_GetItemRectMax", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetItemRectMin = function(ctx)
    log_api_call("ImGui_GetItemRectMin", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetItemRectSize = function(ctx)
    log_api_call("ImGui_GetItemRectSize", ctx)
    -- Return mock values for getter functions
    return 100, 50  -- Mock width, height
  end,

  ImGui_GetKeyDownDuration = function(ctx)
    log_api_call("ImGui_GetKeyDownDuration", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMainViewport = function(ctx)
    log_api_call("ImGui_GetMainViewport", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMouseClickedPos = function(ctx)
    log_api_call("ImGui_GetMouseClickedPos", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetMouseCursor = function(ctx)
    log_api_call("ImGui_GetMouseCursor", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMouseDelta = function(ctx)
    log_api_call("ImGui_GetMouseDelta", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMouseDownDuration = function(ctx)
    log_api_call("ImGui_GetMouseDownDuration", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMouseDragDelta = function(ctx)
    log_api_call("ImGui_GetMouseDragDelta", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetMousePos = function(ctx)
    log_api_call("ImGui_GetMousePos", ctx)
    -- Return mock values for getter functions
    return 10, 20  -- Mock x, y
  end,

  ImGui_GetMouseWheel = function(ctx)
    log_api_call("ImGui_GetMouseWheel", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetScrollMaxX = function(ctx)
    log_api_call("ImGui_GetScrollMaxX", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetScrollMaxY = function(ctx)
    log_api_call("ImGui_GetScrollMaxY", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetScrollX = function(ctx)
    log_api_call("ImGui_GetScrollX", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetScrollY = function(ctx)
    log_api_call("ImGui_GetScrollY", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetStyleColor = function(ctx, color)
    log_api_call("ImGui_GetStyleColor", ctx, color)
    -- Return mock values for getter functions
    return 0xFFFFFFFF  -- Mock color
  end,

  ImGui_GetStyleVar = function(ctx)
    log_api_call("ImGui_GetStyleVar", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetTextLineHeight = function(ctx)
    log_api_call("ImGui_GetTextLineHeight", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetTextLineHeightWithSpacing = function(ctx)
    log_api_call("ImGui_GetTextLineHeightWithSpacing", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetTime = function(ctx)
    log_api_call("ImGui_GetTime", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetTreeNodeToLabelSpacing = function(ctx)
    log_api_call("ImGui_GetTreeNodeToLabelSpacing", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetVersion = function(ctx)
    log_api_call("ImGui_GetVersion", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetWindowContentRegionMax = function(ctx)
    log_api_call("ImGui_GetWindowContentRegionMax", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetWindowDockID = function(ctx)
    log_api_call("ImGui_GetWindowDockID", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetWindowDrawList = function(ctx)
    log_api_call("ImGui_GetWindowDrawList", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetWindowViewport = function(ctx)
    log_api_call("ImGui_GetWindowViewport", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_GetWindowWidth = function(ctx)
    log_api_call("ImGui_GetWindowWidth", ctx)
    -- Return mock values for getter functions
    return 0  -- Mock value
  end,

  ImGui_Image = function(ctx, text)
    log_api_call("ImGui_Image", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_ImageButton = function(ctx, label)
    log_api_call("ImGui_ImageButton", ctx, label)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_Image_GetSize = function(ctx, text, width, height)
    log_api_call("ImGui_Image_GetSize", ctx, text, width, height)
    -- Default virtual implementation
  end,

  ImGui_InputDouble2 = function(ctx, label, value)
    log_api_call("ImGui_InputDouble2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputDouble3 = function(ctx, label, value)
    log_api_call("ImGui_InputDouble3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputDouble4 = function(ctx, label, value)
    log_api_call("ImGui_InputDouble4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputDoubleN = function(ctx, label, value)
    log_api_call("ImGui_InputDoubleN", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputFloat = function(ctx, label, value)
    log_api_call("ImGui_InputFloat", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputInt2 = function(ctx, label, value)
    log_api_call("ImGui_InputInt2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputInt3 = function(ctx, label, value)
    log_api_call("ImGui_InputInt3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputInt4 = function(ctx, label, value)
    log_api_call("ImGui_InputInt4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_InputScalar = function(ctx, label, value)
    log_api_call("ImGui_InputScalar", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_IsAnyItemHovered = function(ctx)
    log_api_call("ImGui_IsAnyItemHovered", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsItemToggledOpen = function(ctx)
    log_api_call("ImGui_IsItemToggledOpen", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsKeyDown = function(ctx)
    log_api_call("ImGui_IsKeyDown", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsKeyPressed = function(ctx)
    log_api_call("ImGui_IsKeyPressed", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMouseClicked = function(ctx)
    log_api_call("ImGui_IsMouseClicked", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMouseDoubleClicked = function(ctx)
    log_api_call("ImGui_IsMouseDoubleClicked", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMouseDown = function(ctx)
    log_api_call("ImGui_IsMouseDown", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMouseDragging = function(ctx)
    log_api_call("ImGui_IsMouseDragging", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMousePosValid = function(ctx, x, y)
    log_api_call("ImGui_IsMousePosValid", ctx, x, y)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsMouseReleased = function(ctx)
    log_api_call("ImGui_IsMouseReleased", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsWindowDocked = function(ctx)
    log_api_call("ImGui_IsWindowDocked", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsWindowFocused = function(ctx)
    log_api_call("ImGui_IsWindowFocused", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_IsWindowHovered = function(ctx)
    log_api_call("ImGui_IsWindowHovered", ctx)
    -- Return false for query functions in virtual mode
    return false
  end,

  ImGui_ListClipper_Begin = function(ctx)
    log_api_call("ImGui_ListClipper_Begin", ctx)
    -- Default virtual implementation
  end,

  ImGui_ListClipper_End = function(ctx)
    log_api_call("ImGui_ListClipper_End", ctx)
    -- Default virtual implementation
  end,

  ImGui_ListClipper_GetDisplayRange = function(ctx)
    log_api_call("ImGui_ListClipper_GetDisplayRange", ctx)
    -- Default virtual implementation
  end,

  ImGui_ListClipper_Step = function(ctx)
    log_api_call("ImGui_ListClipper_Step", ctx)
    -- Default virtual implementation
  end,

  ImGui_LogFinish = function(ctx)
    log_api_call("ImGui_LogFinish", ctx)
    -- Default virtual implementation
  end,

  ImGui_LogText = function(ctx, text)
    log_api_call("ImGui_LogText", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_LogToClipboard = function(ctx)
    log_api_call("ImGui_LogToClipboard", ctx)
    -- Default virtual implementation
  end,

  ImGui_LogToFile = function(ctx)
    log_api_call("ImGui_LogToFile", ctx)
    -- Default virtual implementation
  end,

  ImGui_LogToTTY = function(ctx)
    log_api_call("ImGui_LogToTTY", ctx)
    -- Default virtual implementation
  end,

  ImGui_NextColumn = function(ctx)
    log_api_call("ImGui_NextColumn", ctx)
    -- Default virtual implementation
  end,

  ImGui_NumericLimits_Double = function(ctx)
    log_api_call("ImGui_NumericLimits_Double", ctx)
    -- Default virtual implementation
  end,

  ImGui_NumericLimits_Float = function(ctx)
    log_api_call("ImGui_NumericLimits_Float", ctx)
    -- Default virtual implementation
  end,

  ImGui_OpenPopup = function(ctx)
    log_api_call("ImGui_OpenPopup", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_OpenPopupOnItemClick = function(ctx)
    log_api_call("ImGui_OpenPopupOnItemClick", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_PlotHistogram = function(ctx)
    log_api_call("ImGui_PlotHistogram", ctx)
    -- Default virtual implementation
  end,

  ImGui_PlotLines = function(ctx)
    log_api_call("ImGui_PlotLines", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopButtonRepeat = function(ctx)
    log_api_call("ImGui_PopButtonRepeat", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopClipRect = function(ctx)
    log_api_call("ImGui_PopClipRect", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopID = function(ctx)
    log_api_call("ImGui_PopID", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopItemWidth = function(ctx)
    log_api_call("ImGui_PopItemWidth", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopTabStop = function(ctx)
    log_api_call("ImGui_PopTabStop", ctx)
    -- Default virtual implementation
  end,

  ImGui_PopTextWrapPos = function(ctx, x, y)
    log_api_call("ImGui_PopTextWrapPos", ctx, x, y)
    -- Default virtual implementation
  end,

  ImGui_ProgressBar = function(ctx)
    log_api_call("ImGui_ProgressBar", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushButtonRepeat = function(ctx)
    log_api_call("ImGui_PushButtonRepeat", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushClipRect = function(ctx)
    log_api_call("ImGui_PushClipRect", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushID = function(ctx)
    log_api_call("ImGui_PushID", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushItemWidth = function(ctx)
    log_api_call("ImGui_PushItemWidth", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushTabStop = function(ctx)
    log_api_call("ImGui_PushTabStop", ctx)
    -- Default virtual implementation
  end,

  ImGui_PushTextWrapPos = function(ctx, x, y)
    log_api_call("ImGui_PushTextWrapPos", ctx, x, y)
    -- Default virtual implementation
  end,

  ImGui_ResetMouseDragDelta = function(ctx, label, value)
    log_api_call("ImGui_ResetMouseDragDelta", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SetColorEditOptions = function(ctx, value, color)
    log_api_call("ImGui_SetColorEditOptions", ctx, value, color)
    -- Default virtual implementation
  end,

  ImGui_SetConfigVar = function(ctx, value)
    log_api_call("ImGui_SetConfigVar", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetCursorPosX = function(ctx, value, x, y)
    log_api_call("ImGui_SetCursorPosX", ctx, value, x, y)
    -- Default virtual implementation
  end,

  ImGui_SetCursorScreenPos = function(ctx, value, x, y)
    log_api_call("ImGui_SetCursorScreenPos", ctx, value, x, y)
    -- Default virtual implementation
  end,

  ImGui_SetDragDropPayload = function(ctx, value)
    log_api_call("ImGui_SetDragDropPayload", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetItemDefaultFocus = function(ctx, value)
    log_api_call("ImGui_SetItemDefaultFocus", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetKeyboardFocusHere = function(ctx, value)
    log_api_call("ImGui_SetKeyboardFocusHere", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetMouseCursor = function(ctx, value)
    log_api_call("ImGui_SetMouseCursor", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextFrameWantCaptureKeyboard = function(ctx, value)
    log_api_call("ImGui_SetNextFrameWantCaptureKeyboard", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextFrameWantCaptureMouse = function(ctx, value)
    log_api_call("ImGui_SetNextFrameWantCaptureMouse", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextItemAllowOverlap = function(ctx, value)
    log_api_call("ImGui_SetNextItemAllowOverlap", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextItemOpen = function(ctx, value)
    log_api_call("ImGui_SetNextItemOpen", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextItemShortcut = function(ctx, value)
    log_api_call("ImGui_SetNextItemShortcut", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextItemWidth = function(ctx, value)
    log_api_call("ImGui_SetNextItemWidth", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextWindowBgAlpha = function(ctx, value)
    log_api_call("ImGui_SetNextWindowBgAlpha", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextWindowContentSize = function(ctx, value, width, height)
    log_api_call("ImGui_SetNextWindowContentSize", ctx, value, width, height)
    -- Default virtual implementation
  end,

  ImGui_SetNextWindowDockID = function(ctx, value)
    log_api_call("ImGui_SetNextWindowDockID", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetNextWindowSizeConstraints = function(ctx, value, width, height)
    log_api_call("ImGui_SetNextWindowSizeConstraints", ctx, value, width, height)
    -- Default virtual implementation
  end,

  ImGui_SetScrollFromPosX = function(ctx, value, x, y)
    log_api_call("ImGui_SetScrollFromPosX", ctx, value, x, y)
    -- Default virtual implementation
  end,

  ImGui_SetScrollFromPosY = function(ctx, value, x, y)
    log_api_call("ImGui_SetScrollFromPosY", ctx, value, x, y)
    -- Default virtual implementation
  end,

  ImGui_SetScrollHereX = function(ctx, value)
    log_api_call("ImGui_SetScrollHereX", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetScrollHereY = function(ctx, value)
    log_api_call("ImGui_SetScrollHereY", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetScrollX = function(ctx, value)
    log_api_call("ImGui_SetScrollX", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetScrollY = function(ctx, value)
    log_api_call("ImGui_SetScrollY", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetWindowFontScale = function(ctx, value)
    log_api_call("ImGui_SetWindowFontScale", ctx, value)
    -- Default virtual implementation
  end,

  ImGui_SetWindowSize = function(ctx, value, width, height)
    log_api_call("ImGui_SetWindowSize", ctx, value, width, height)
    -- Default virtual implementation
  end,

  ImGui_Shortcut = function(ctx)
    log_api_call("ImGui_Shortcut", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowAboutWindow = function(ctx)
    log_api_call("ImGui_ShowAboutWindow", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowDebugLogWindow = function(ctx)
    log_api_call("ImGui_ShowDebugLogWindow", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowFontAtlas = function(ctx)
    log_api_call("ImGui_ShowFontAtlas", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowFontSelector = function(ctx)
    log_api_call("ImGui_ShowFontSelector", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowIDStackToolWindow = function(ctx)
    log_api_call("ImGui_ShowIDStackToolWindow", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowMetricsWindow = function(ctx)
    log_api_call("ImGui_ShowMetricsWindow", ctx)
    -- Default virtual implementation
  end,

  ImGui_ShowStyleSelector = function(ctx)
    log_api_call("ImGui_ShowStyleSelector", ctx)
    -- Default virtual implementation
  end,

  ImGui_SliderAngle = function(ctx, label, value)
    log_api_call("ImGui_SliderAngle", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderDouble2 = function(ctx, label, value)
    log_api_call("ImGui_SliderDouble2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderDouble3 = function(ctx, label, value)
    log_api_call("ImGui_SliderDouble3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderDouble4 = function(ctx, label, value)
    log_api_call("ImGui_SliderDouble4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderDoubleN = function(ctx, label, value)
    log_api_call("ImGui_SliderDoubleN", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderInt2 = function(ctx, label, value)
    log_api_call("ImGui_SliderInt2", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderInt3 = function(ctx, label, value)
    log_api_call("ImGui_SliderInt3", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderInt4 = function(ctx, label, value)
    log_api_call("ImGui_SliderInt4", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_SliderScalar = function(ctx, label, value)
    log_api_call("ImGui_SliderScalar", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_StyleColorsClassic = function(ctx, color)
    log_api_call("ImGui_StyleColorsClassic", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_StyleColorsLight = function(ctx, color)
    log_api_call("ImGui_StyleColorsLight", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_TabItemButton = function(ctx, label)
    log_api_call("ImGui_TabItemButton", ctx, label)
    -- Return false for interactive widgets in virtual mode
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false
  end,

  ImGui_TableAngledHeadersRow = function(ctx)
    log_api_call("ImGui_TableAngledHeadersRow", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableFlags_NoBordersInBody = function(ctx, flags)
    log_api_call("ImGui_TableFlags_NoBordersInBody", ctx, flags)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableFlags_NoBordersInBodyUntilResize = function(ctx, flags)
    log_api_call("ImGui_TableFlags_NoBordersInBodyUntilResize", ctx, flags)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableGetColumnFlags = function(ctx, flags)
    log_api_call("ImGui_TableGetColumnFlags", ctx, flags)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableGetColumnIndex = function(ctx)
    log_api_call("ImGui_TableGetColumnIndex", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableGetColumnName = function(ctx)
    log_api_call("ImGui_TableGetColumnName", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableGetColumnSortSpecs = function(ctx)
    log_api_call("ImGui_TableGetColumnSortSpecs", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableGetRowIndex = function(ctx)
    log_api_call("ImGui_TableGetRowIndex", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableHeader = function(ctx)
    log_api_call("ImGui_TableHeader", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableHeadersRow = function(ctx)
    log_api_call("ImGui_TableHeadersRow", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableNeedSort = function(ctx)
    log_api_call("ImGui_TableNeedSort", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableNextColumn = function(ctx)
    log_api_call("ImGui_TableNextColumn", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableNextRow = function(ctx)
    log_api_call("ImGui_TableNextRow", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableSetBgColor = function(ctx, color)
    log_api_call("ImGui_TableSetBgColor", ctx, color)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableSetColumnIndex = function(ctx)
    log_api_call("ImGui_TableSetColumnIndex", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableSetupColumn = function(ctx)
    log_api_call("ImGui_TableSetupColumn", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TableSetupScrollFreeze = function(ctx)
    log_api_call("ImGui_TableSetupScrollFreeze", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TextFilter_Draw = function(ctx, text)
    log_api_call("ImGui_TextFilter_Draw", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_TextFilter_IsActive = function(ctx, text)
    log_api_call("ImGui_TextFilter_IsActive", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_TextFilter_PassFilter = function(ctx, text)
    log_api_call("ImGui_TextFilter_PassFilter", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_TextUnformatted = function(ctx, text)
    log_api_call("ImGui_TextUnformatted", ctx, text)
    -- Default virtual implementation
  end,

  ImGui_TreeNode = function(ctx)
    log_api_call("ImGui_TreeNode", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TreeNodeEx = function(ctx)
    log_api_call("ImGui_TreeNodeEx", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_TreePop = function(ctx)
    log_api_call("ImGui_TreePop", ctx)
    -- Default virtual implementation
    return false
  end,

  ImGui_VSliderDouble = function(ctx, label, value)
    log_api_call("ImGui_VSliderDouble", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_VSliderInt = function(ctx, label, value)
    log_api_call("ImGui_VSliderInt", ctx, label, value)
    -- Return unchanged value for input widgets
    VirtualState.stats.widgets_drawn = VirtualState.stats.widgets_drawn + 1
    return false, value or 0
  end,

  ImGui_ValidatePtr = function(ctx)
    log_api_call("ImGui_ValidatePtr", ctx)
    -- Default virtual implementation
  end,

  ImGui_Viewport_GetCenter = function(ctx)
    log_api_call("ImGui_Viewport_GetCenter", ctx)
    -- Default virtual implementation
  end,

  ImGui_Viewport_GetPos = function(ctx, x, y)
    log_api_call("ImGui_Viewport_GetPos", ctx, x, y)
    -- Default virtual implementation
  end,

  ImGui_Viewport_GetWorkPos = function(ctx, x, y)
    log_api_call("ImGui_Viewport_GetWorkPos", ctx, x, y)
    -- Default virtual implementation
  end,

  ImGui_Viewport_GetWorkSize = function(ctx, width, height)
    log_api_call("ImGui_Viewport_GetWorkSize", ctx, width, height)
    -- Default virtual implementation
  end,
